version: "3.7"
services:
  recommendation:
    container_name: project1
    image: project1:1.0
    #build: .
    restart: always #on-failure
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]